### ISSUE TITLE
A way for us in the repo to report what we're working on

### ISSUE THREAD

**Issue by wdya** [Roundtable-Hold/tracker#11]
A few times now I've gotten halfway through creating a new page, or even finished it and started uploading it, then discovered someone else was making the same thing and added it moments ago. (e.g. last night, I checked the site and saw no page for Crystal Tears, so I took a couple hours and made a complete page, and by the time I finished and went to upload it, someone had already done exactly the same thing.) I think as more people start working on this, it'd be great if we can report when we start something so someone else doesn't also start it. Or are we doing that already and I haven't known where to look for it?

**Comment by thomasgraham18** [comment]
Currently working on Talismans :)

**Comment by wdya** [comment]
> Currently working on Talismans :)

Appreciate the heads up! I was considering that for my next thing lol. I'll do some more NPC quests

**Comment by azy2** [comment]
We could definitely use projects but I believe people need to be added to the organization before they can add to a project which introduces a barrier of entry where they have to wait for one of us to add them.
