### ISSUE TITLE
Item Issues / Missing Weapons

### ISSUE THREAD

**Issue by ZKjellberg** [Roundtable-Hold/tracker#19]
I discovered this guide today and was impressed with the amount of work migrating from the original Dark Souls 3 guide for Elden Ring. Awesome work.

I went through this evening to check off my items to get familiar with the new design and encountered the following issues:

- [x] ~1. Missing [Great Runes](https://eldenring.wiki.fextralife.com/Great+Runes) Section~
- [x] ~2. For sorceries, multiple spells are merged to a single bullet. Troublesome for people who have only bought a single spell out of the bundle.~
- [x] ~3. Filter is not working for Talismans & Crystal Tears & Achievements due to missing filter ID~
- [ ] 4. Reviewing the weapons section, the following weapon categories are missing:

* https://eldenring.wiki.fextralife.com/Flails
* https://eldenring.wiki.fextralife.com/Spears
* https://eldenring.wiki.fextralife.com/Fists
* https://eldenring.wiki.fextralife.com/Halberds
* https://eldenring.wiki.fextralife.com/Straight+Swords
* https://eldenring.wiki.fextralife.com/Thrusting+Swords
* https://eldenring.wiki.fextralife.com/Heavy+Thrusting+Swords
* https://eldenring.wiki.fextralife.com/Greataxes
* https://eldenring.wiki.fextralife.com/Hammers
* https://eldenring.wiki.fextralife.com/Great+Hammers
* https://eldenring.wiki.fextralife.com/Reapers
* https://eldenring.wiki.fextralife.com/Twinblades
* https://eldenring.wiki.fextralife.com/Katanas
* https://eldenring.wiki.fextralife.com/Sacred+Seals
* https://eldenring.wiki.fextralife.com/Glintstone+Staffs
* While the Bows category exists, it is missing the following categories & weapon
  * https://eldenring.wiki.fextralife.com/Light+Bows
  * https://eldenring.wiki.fextralife.com/Greatbows
  * Missing Greatbow

**Comment by azy2** [comment]
3 is fixed.

I believe 4 is being worked on by Quivorian.

If someone wants to take up 1 and 2 that would be great. Please make a new issue and assign yourself to it once you begin working.

**Comment by ZKjellberg** [comment]
@Quivorian I've pushed up PR #25 to start the missing weapons, with bows first addressed.

[I set up a staging branch for the missing weapon categories](https://github.com/ZKjellberg/tracker/commit/093cb9a6d764ae3d6e6046829b4cb9301fc12960)

I would like to revamp the weapons to be in the order the game presents by Type, so all ranged weapons are in sequential order, compared to Fextralife's alphabetical.

**Comment by ZKjellberg** [comment]
See below for weapon order. Starting to work on my branch to get the headers in order, so we can start the transition of weapons afterwards.

1. Dagger
2. Short Sword
3. Straight Sword
4. Greatsword
5. Colossal Sword
6. Thrusting Sword
7. Heavy Thrusting Sword
8. Curved Sword
9. Curved Greatsword
10. Katana
11. Twinblade
12. Axe
13. Greataxe
14. Hammer
15. Flail
16. Great Hammer
17. Spear
18. Great Spear
19. Halberd
20. Repeer
21. Whip
22. Fist
23. Claw
24. Light Bow
25. Bow
26. Greatbow
27. Crossbow
28. Ballista
29. Glintstone Staff
30. Sacred Seal
31. Torch
32. Small Shield
33. Medium Shield
34. Great Shield

**Comment by ZKjellberg** [comment]
My `19-weapons2` branch is now updated with the weapon categories matching the game order.

The only category I was unsure of was Colossal weapons. I do not have one to confirm the ordering, but assumed it'd be after Colossal Swords.

[19-weapons2](https://github.com/ZKjellberg/tracker/commit/093cb9a6d764ae3d6e6046829b4cb9301fc12960)

@Quivorian We can discuss later on best path forward to start adding weapons.

**Comment by ZKjellberg** [comment]
See here for the current active branch that will be used to collaborate on the implementation:
https://github.com/Roundtable-Hold/tracker/tree/19-weapons2

**Comment by ZKjellberg** [comment]
Further progress here:
https://github.com/ZKjellberg/tracker/commit/03332e9ac94a0bbf268029f3fc640e87beba816d

This is going to take some time, as just straight swords has 19 entries.
