### ISSUE TITLE
Add nearest grace to main walkthrough tracker events

### ISSUE THREAD

**Issue by ankushg** [Roundtable-Hold/tracker#24]
If you're not following everything in exact order, it's really confusing to understand what each point it talking about because they don't have a lot of context

It'd be a lot easier if there was a spoiler-tagged option to see the nearest grace site for each item

**Comment by azy2** [comment]
This is something we've been asked about a lot. It's unlikely to happen anytime soon. Sorting by nearest grace would be technically very challenging to implement. Sorry about that.
