### ISSUE TITLE
Gestures page does not fit on mobile displays

### ISSUE THREAD

**Issue by azy2** [Roundtable-Hold/tracker#26]
The gestures table is too wide and forces phones to horizontal scroll. The table needs to be reworked. Ideally into a list.

**Comment by wdya** [comment]
The "questline" column isn't strictly necessary; I could go through the file and get rid of that pretty quickly if having a fourth column is what's making it too wide.

**Comment by azy2** [comment]
This is fixed by responsive tables that I recently checked in. No need to change anything.

**Comment by azy2** [comment]
@wdya btw please join the new discord channel. There's a link in the ReadMe
