### ISSUE TITLE
Nepheli Loux Questline Correction (+ Kenneth Haight Questline)

### ISSUE THREAD

**Issue by Smaxtr** [Roundtable-Hold/tracker#3]
First Note, the questline is not incomplete.

What you have to do is first of course complete Nepheli's Quest and give her the Ashes and do the Kenneth Haight Questline.

Since I don't see it on the Tracker as well I give you a Quick Run Down.

- Find Kenneth in Limgrave on top of a Fallen Structure, he will ask for help to get back Fort Haight.
- Go to Fort Haight (South from Mistwood, down the road)  and clear it. On the way you can pick up the Dectus Medallion (Left)
- Go back to Kenneth and bring him the good news and get an Erdsteel Dagger, Exhaust his dialogue and Accept his Accord.
- Go back to Fort Haight, now inhabit by Demihumans with Kenneth on top of the Fort where you fought the Night. Exhaust the Dialogue there too.

Done here and have to defeat Godrick the Grafted and then you need to defeat Morgott, The Omen King.
After you've done all that go to Godrick's Site of Grace and rest there 2 - 3 times. (Didn't work for me at first, I also payed a visit on both Nepehli and Kenneth again just to be sure)
They then move in the Throne Room, Nepehli will give you a Ancient Dragon Smithing Stone if you talk to her.
Also if you did not kill Gatekeeper Gostoc he will reopen his Shop and sell another Ancient Dragon Smithing Stone.

**Comment by wdya** [comment]
Working on this now

**Comment by wdya** [comment]
Btw, the questline was indeed incomplete or bugged before patch 1.03 - this conclusion to it is only possible since then

**Comment by azy2** [comment]
@wdya is this resolved now? If so can you close this issue.

**Comment by wdya** [comment]
> @wdya is this resolved now? If so can you close this issue.

I don't believe I can - I have a button to unassign myself but nothing to close the issue. It is complete, though.
